### ISSUE TITLE
Pood

### ISSUE THREAD

**Issue by mikroskeem** [mikroskeem/msb-tracker#3]
Serveril on olemas poe ehitis ning ka sinna teleporteerumiseks loodud _warp_, aga pood pole valmis.

Vajalikud tööd:
- [x] Normaalne plugin poe jaoks
- [x] Mõtle välja poes müüdavad esemed

Siia alla saab soovitada müüdavaid esemeid koos hindadega.

**Comment by DirolGaming** [comment]
Ise sai proovida sellist pluginat, nagu [ShopChest](https://www.spigotmc.org/resources/shopchest.11431/).
Toimis minul suurepäraselt ja on vägagi omapärase disainiga ja vaadates sinu serverit, siis disaini ja välimuse poolest sobiks see plugin ka sinu serverile suurepäraselt. Ei tea, kas oled seda proovinud või mitte.

**Comment by mikroskeem** [comment]
ShopChesti ei õnnestunud tööle saada serveris, hoopis SignShop läks kasutusse.  
Poes müüdavad esemed on ka enam-vähem koos hindadega paigas.
